replicaCount: 2
image:
  repository: ghcr.io/raisin-run/raisin-console
  tag: latest
service:
  port: 3000
ingress:
  host: app.raisin.run
env:
  RAISIN_API_URL: http://raisin-api
  NEXT_PUBLIC_API_URL: https://api.raisin.run
  BETTER_AUTH_URL: https://app.raisin.run
