apiVersion: v1
kind: ServiceAccount
metadata:
  name: raisin-api
  annotations:
    {{- if .Values.global.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.global.irsaRoleArn | quote }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raisin-worker
  annotations:
    {{- if .Values.global.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.global.irsaRoleArn | quote }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raisin-smtp
